### ISSUE TITLE
Tanker om action

### ISSUE THREAD

**Issue by NegatioN** [nrkno/github-action-vault-to-k8s-config#5]
Før jeg prøver å lage noe PR er det kanskje lurt å høre hva vi er enige og uenige om @mikkelnygard 
Dette er det jeg ville endret om det var fritt frem:

1. Det burde være så få required config-options som mulig, og logiske defaults. Jeg ville håndert disse parameterne under som faste regler som Plattform-teamet kontrollerer, hvor det er likt på tvers av alle cluster. (Om mulig)  Om det blir helt utdatert har man uansett god kontroll på hvordan det kan oppdateres via denne actionen om alle bruker den.
```
  ca-cert-path:
  ca-cert-key:
  cluster-host-path: 
  cluster-host-key: 
```
2. Jeg ville kombinert generering av kubeconfig og setting av context. Jeg kan ikke se for meg at jeg ville lagd en config, og ikke brukt den etterpå, så det å dele det opp i to steg føles overflødig.
3. Jeg syns det kun burde være én måte å bruke actionen på. Dvs, ikke mulighet for ***både*** kubeconfig og service-account signins.

Min nåværende example usage for [actionen jeg laget](https://github.com/nrkno/anb-models/blob/a5c039461c8f5a516890b68d923a2b07179ea41f/.github/actions/configged-kubectl/action.yml) er slik, og den føles ganske konsis:
```
- uses: nrkno/anb-models/.github/actions/configged-kubectl@master
  with:
    role: my-role-prod
    namespace: my-namespace
    context: my-cluster
    vault-url: ${VAULT_URL}
```
VS
```
- uses: nrkno/vault-to-k8s-config
  id: vault-to-k8s-config
  with:
    vault-address: https://vault.your.com:8200
    vault-role: your-github-applications-vault-role
    cluster-name: your-cluster
    cluster-namespace: your-namespace
    ca-cert-path: path/to/secret/with/ca-cert/in/vault
    ca-cert-key: key-of-ca-cert-in-secret
    cluster-host-path: path/to/secret/with/api-url/in/vault
    cluster-host-key: key-of-api-url-in-secret
- uses: azure/k8s-set-context@v3
  with:
     method: kubeconfig
     kubeconfig: ${{ steps.vault-to-k8s-config.outputs.k8s-config }}
```

Er dette helt forskjellig fra du tenker, eller er vi på sånn ca samme spor?
